# This workflow will build a docker container, publish it to Google Container Registry, and deploy it to Cloud Run when there is a push to the "main" branch.
#
# To configure this workflow:
#
# 1. Create and configure a Workload Identity Provider for GitHub (https://github.com/google-github-actions/auth#setting-up-workload-identity-federation)
#
# 2. Change the values for the GAR_LOCATION, IMAGE, REPOSITORY and CLOUD_RUN_NAME environment variables (below).

name: Build and Deploy to Cloud Run

on:
  push:
    branches: [ "main" ]

env:
  PROJECT_ID: ${{ secrets.PROJECT_ID }}
  GAR_LOCATION: us-central1 # TODO: update region of the Artifact Registry
  REPOSITORY: artifact-registry-datasus # TODO: update to Artifact Registry docker repository
  IMAGE: datasus-image
  CLOUD_RUN: datasus-cloudrun

jobs:
  setup-build-publish-deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    # Configure Workload Identity Federation and generate an access token.
    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v2'
      with:
        token_format: 'access_token'
        workload_identity_provider: '${{secrets.WIF_PROVIDER}}'
        service_account: '${{secrets.WIF_SERVICE_ACCOUNT}}'

    - name: Docker configuration
      run: |-
        echo ${{steps.auth.outputs.access_token}} | docker login -u oauth2accesstoken --password-stdin https://$GAR_LOCATION-docker.pkg.dev

    # Build the Docker image
    - name: Build
      run: |-
        docker build \
          --tag "$GAR_LOCATION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/$IMAGE:$GITHUB_SHA" \
          --build-arg GITHUB_SHA="$GITHUB_SHA" \
          --build-arg GITHUB_REF="$GITHUB_REF" \
          .
    # Push the Docker image to Google Artifact Registry
    - name: Publish
      run: |-
        docker push "$GAR_LOCATION-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/$IMAGE:$GITHUB_SHA"

    #Update Cloud Run to use new image
    - name: Update Cloud Run
      id: deploy
      run: |-
        gcloud run services update $CLOUD_RUN \
            --region="us-central1" \
            --image="us-central1-docker.pkg.dev/$PROJECT_ID/$REPOSITORY/$IMAGE"
        gcloud run services update-traffic $CLOUD_RUN --to-latest --region=us-central1

    - name: Show Output
      run: echo ${{steps.deploy.outputs.url }}

